%% Do not edit this file
%% loading data

close all; clear all; clc;

im = imread('./sonnet.png');
if(size(im,3) == 3)
    im = rgb2gray(im);
end
im = im2double(im);

sz1 = 15;
threshold = 0.03;
nbins = 256;

%% simple thresholding


%% adaptive thresholding

bw2 = adaptive_thresholding(im,sz1,threshold);

%% display the results
figure;
subplot 121; imshow(im); title('Original image');
subplot 122; imshow(bw2); title('Adaptive thresholding');